### ISSUE TITLE
[Cody Ignore] Update Sidebar UI with Cody Ignore changes

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1256]
Other UI guidance about open files should basically be met by #1253 .

```[tasklist]
### Tasks
- [x] Commands: Add banner #1432
- [x] Commands: Disable buttons #1432
- [ ] Repo selector: Repo is listed but is disabled with a label/message saying it is ignored
- [x] At-mentions:  File is shown but is disabled with a label/message saying it is ignored. Okay if file is excluded from fuzzy @-mention filtering.
- [x] Confirm JetBrains doesn't/won't add for GA a right click on a file, add to chat affordance
```

Adapted from [Figma](https://www.figma.com/file/m9Yvgv6W3aPRLfXnxgwnEz/JetBrains?type=design&node-id=1297-78439&mode=design&t=8YgkN0zf2728hX74-0) and @toolmantim 's summary of [product interactions in the RFC:](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit#bookmark=id.8smvyvjidz0a)

**Comment by danielmarquespt** [comment]
Relevant UX direction on this issue
https://github.com/sourcegraph/jetbrains/issues/1253#issuecomment-2057055486

**Comment by danielmarquespt** [comment]
> @ mentioning an ignored file in the message input ⇒ File is shown but is disabled with a label/message saying it is ignored. Okay if file is excluded from fuzzy @-mention filtering.

AFAIK this is not a requirement since @-mentioning is only available for Current-repo files, and blocking chat all together for ignored repos means that @mentioning is not possible
