### ISSUE TITLE
Update hotkeys and make them more discoverable

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1477]
| Command | Windows / Linux | MacOs |
| -- | -- | -- |
| **Chat** |  |  |
| New Chat | Alt + = | Option + = |
| Open Chat | Alt + - | Option + - |
| **Autocompletions** |  |  |
| Generate an autocompletion | Alt + `\` | option + `\` |
| Cycle through autocompletions | Alt + `]` or `[` | option + `]` or `[` |
| Accept autocompletion | tab | tab |
| **Commands** |  |  |
| Explain Code | Alt + Shift + 1 | control + Shift + E |
| Smell Code | Alt + Shift + 2 | control + Shift + S |
| Generate Unit Test | Alt + Shift + 3 | control + Shift + T |
| Edit Code | TODO | control + Shift + Enter |
| Document Code | TODO | control + Shift + H |
| **Code Lenses** |  |  |
| Accept | Control + Shift + = | Command + Shift + = |
| Undo | Control + Shift + Delete | Control + Shift + Delete |
| Edit & Retry | Control + Shift + Enter | Control + Shift + Enter |
| Show Diff | Command + Shift + ' | Command + Shift + ' |

Hotkey discussion:

* How can I find the existing hotkeys for Windows?
* The hotkey for document doesn't seem to be implemented yet, and is there a reason it's `x` instead of `d` for "document"?
* Should we/can we also replace the `command` keybinding with `ctrl` for executing document and accept/view diff? It feels clunky that there's a mix. Or should/can we use `command` for everything? Feedback from Julie: moving between `ctrl` for commands and `command` for completions is difficult to get used to. Has anyone else felt this? At least for me, it's easier to get my fingers to the `command` button than to the `control` button.
* [Feedback](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1715193789187509) from Julie: for multi-line prompts, using the `arrow up` key to edit her prompt ends up moving her backwards in history. This seems like a pretty likely use case. Should we add support for something like `shift + arrow up` to edit the text box, or turn off the cycle-through-history functionality once a user has entered text?
* Additional feedback from Julie: Keyboard shortcuts for accept/undo/edit/view diff are complex. Are `ctrl + a` (for accept), `ctrl + u` (for undo), and `ctrl + d` (diff) available, or is there another way we could simplify these shortcuts into just two keys?

Discoverability:

* Whatever we land on for keybindings, we need to add them to the buttons and the context menu for better discoverability.

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/e790ce50-7725-452a-ae55-b429cfe49f9b/c578e6e2-7307-40a1-8f27-6180a57df24f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9lNzkwY2U1MC03NzI1LTQ1MmEtYWU1NS1iNDI5Y2ZlNDlmOWIvYzU3OGU2ZTItNzMwNy00MGExLThmMjctNjE4MGE1N2RmMjRmIiwiaWF0IjoxNzE1MzM0NzgxLCJleHAiOjMzMjg1ODk0NzgxfQ.kPTcPN9XQmtMihYgKVYIX6Ia1AzxPYBX14gzUu188PA)

![Image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/94b031bf-ada9-4c08-857f-4f9fcc5f24bf/4039bf12-1d37-4bca-9ce2-eef69d243ae6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy85NGIwMzFiZi1hZGE5LTRjMDgtODU3Zi00ZjlmY2M1ZjI0YmYvNDAzOWJmMTItMWQzNy00YmNhLTljZTItZWVmNjlkMjQzYWU2IiwiaWF0IjoxNzE1MzM0NzgxLCJleHAiOjMzMjg1ODk0NzgxfQ.DNhwW7aH5HqFOpaVy2ZDcIowv_kgSGCjd1nskBdHoRA)

```[tasklist]
### TODO:
- [ ] Align on hotkeys (including Windows)
- [ ] Update ghost text if any of those hotkeys change
- [ ] Implement hotkey for document
- [ ] Update UX for discoverability
- [ ] Update docs
- [ ] Update `TESTING.md`
```

**Comment by danielmarquespt** [comment]
> How can I find the existing hotkeys for Windows?

We need to include them in the command tab. But they are part of the context menu

> The hotkey for document doesn't seem to be implemented yet, and is there a reason it's x instead of d for "document"?

Me and @steveyegge where think of ctrl + shift + H for document. Because its easy to reach with two hands and its an open combination

>Should we/can we also replace the command keybinding with ctrl for executing document and accept/view diff? It feels clunky that there's a mix. Or should/can we use command for everything? 

Yes we should use CTRL for those options. Regarding why ctrl and not command: Command is taken for most combinations, and control is not :/

>[Feedback](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1715193789187509) from Julie: for multi-line prompts, using the arrow up key to edit her prompt ends up moving her backwards in history. This seems like a pretty likely use case. Should we add support for something like shift + arrow up to edit the text box, or turn off the cycle-through-history functionality once a user has entered text?

This used to be a problem in the sidebar as well and its fixed, we just need to mimic the behaviour

>Additional feedback from Julie: Keyboard shortcuts for accept/undo/edit/view diff are complex. Are ctrl + a (for accept), ctrl + u (for undo), and ctrl + d (diff) available, or is there another way we could simplify these shortcuts into just two keys?

I'll think about these

**Comment by taylorsperry** [comment]
Some very brief testing suggests that `command + z` already works as an undo shortcut 🤔

**Comment by taylorsperry** [comment]
@danielmarquespt I've gone into settings > keymaps > Cody and selected Eclipse (not the macOS option) and updated what *I think* are the existing keybindings for Windows. Is there a better way to check that from a Mac machine, or can you double-check me? And did you have any luck finding any simpler shortcuts? 

I'd like to have a master list of Cody shortcuts on our docs page and also share with QA to make sure they're working correctly. 

And @steveyegge do the Document and Edit shortcuts still need to be implemented for Windows?

**Comment by dominiccooney** [comment]
Here's the keymap from a Windows machine with Cody, per the instructions @danielmarquespt sent on Slack:

[keymap.csv](https://github.com/sourcegraph/jetbrains/files/15337502/keymap.csv)

**Comment by kalanchan** [comment]
Related to https://github.com/sourcegraph/jetbrains/issues/1709, we need to revisit the window shortcuts as some of them don't work (undo & accept, and edit)

@danielmarquespt could you revisit the all window shortcuts, we need to the reconsider the [JetBrains window keymaps](https://github.com/JetBrains/intellij-community/tree/master/platform/platform-resources/src/keymaps). 

related: @dominiccooney's [comment ](https://github.com/sourcegraph/jetbrains/issues/1709#issuecomment-2141839651)

**Comment by taylorsperry** [comment]
Tested GoLand on 6.0.3 on Mac and the Show Diff hotkey `command shift '` doesn't seem to be working https://github.com/sourcegraph/cody-issues/issues/270.

The code lens for Accept doesn't have the `control shift =` hint, but the hotkey works.

**Comment by taylorsperry** [comment]
Related issue if it's easy enough to add "while we're at it" https://github.com/sourcegraph/cody-issues/issues/309
