### ISSUE TITLE
JetBrains: model error states in cody status

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#22]
```[tasklist]
### Tasks
- [x] JetBrains: add visual hint in status bar when user is not logged in
- [x] JetBrains: add visual hint when agent not running
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57579
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56050
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56455
- [ ] https://github.com/sourcegraph/sourcegraph/issues/57506
- [ ] https://github.com/sourcegraph/sourcegraph/issues/56618
```

**Comment by taylorsperry** [comment]
Closing this since there's only one outstanding issue here, which I'm giving a status of "To consider in planning."
