### ISSUE TITLE
Notes from testing the latest nightly plugin

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#331]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/jetbrains/issues/332
- [ ] https://github.com/sourcegraph/jetbrains/issues/337
- [ ] https://github.com/sourcegraph/jetbrains/issues/338
- [ ] https://github.com/sourcegraph/jetbrains/issues/333
- [ ] https://github.com/sourcegraph/jetbrains/issues/334
- [ ] https://github.com/sourcegraph/jetbrains/issues/336
- [ ] https://github.com/sourcegraph/jetbrains/issues/328
- [ ] https://github.com/sourcegraph/jetbrains/issues/339
- [ ] https://github.com/sourcegraph/jetbrains/issues/340
- [ ] https://github.com/sourcegraph/jetbrains/issues/341
- [ ] Cody icon is not spinning while computing autocomplete responses from automatic triggers
- [ ] https://github.com/sourcegraph/jetbrains/issues/346
- [ ] https://github.com/sourcegraph/jetbrains/issues/347
- [ ] https://github.com/sourcegraph/jetbrains/issues/348
- [ ] Confusing behavior when I trigger two commands in a row (likely solved with multi-chat)
```

**Comment by kalanchan** [comment]
going to close this for now olaf, feel free to reopen if you want to do another round of testing
